name: golangci
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/go.mod'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/go.mod'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Download Flux manifests
        run: make manifests
      - name: Run tidy
        run: make tidy
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make tidy and commit changes'
            exit 1
          fi
      - uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5.3.0
        with:
          version: latest
          skip-pkg-cache: true
          args: --timeout=10m
