name: golangci
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/go.mod'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - '**/go.mod'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 1.23.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Download Flux manifests
        run: make manifests
      - name: Run tidy
        run: make tidy
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make tidy and commit changes'
            exit 1
          fi
      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: latest
          skip-pkg-cache: true
          args: --timeout=10m
